name: Python Tests (pytest + coverage via uv)
description: Run pytest with coverage using uv + pyproject.toml
branding:
  icon: check-circle
  color: blue

inputs:
  python-version:
    description: Python version to use
    required: false
    default: "3.12"
  working-directory:
    description: Directory to run tests from
    required: false
    default: "."
  uv-sync-args:
    description: Extra args for `uv sync` (e.g., --group dev)
    required: false
    default: "--all-extras"
  pytest-args:
    description: Extra args for pytest
    required: false
    default: ""

outputs:
  tests_passed:
    description: "true/false"
    value: ${{ steps.mark.outputs.passed }}
  coverage_pct:
    description: "coverage percentage as integer (e.g. 87)"
    value: ${{ steps.cover.outputs.pct }}

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v1

    - name: Resolve & install project deps (pyproject.toml)
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # If you keep a lockfile, you can add --frozen/--locked.
        uv sync ${{ inputs.uv-sync-args }}

    - name: Run pytest with coverage
      id: run
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -euo pipefail
        uv run pytest --maxfail=1 --disable-warnings \
          --cov=. --cov-report=term-missing --cov-report=xml \
          ${{ inputs.pytest-args }} | tee pytest-output.txt

    - name: Extract coverage %
      id: cover
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [[ ! -f coverage.xml ]]; then
          echo "pct=0" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        pct=$(python - <<'PY'
        import xml.etree.ElementTree as ET
        rate = 0.0
        try:
            rate = float(ET.parse("coverage.xml").getroot().attrib.get("line-rate","0"))
        except Exception:
            pass
        print(int(round(rate*100)))
        PY
        )
        echo "pct=$pct" >> "$GITHUB_OUTPUT"

    - name: Mark pass/fail
      id: mark
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "passed=true" >> "$GITHUB_OUTPUT"

    - name: Upload test logs & coverage
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts-${{ inputs.python-version }}
        path: |
        ${{ inputs.working-directory }}/pytest-output.txt
        ${{ inputs.working-directory }}/coverage.xml
