name: tests
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write  # needed for committing badges
  id-token: write 

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.12']

    steps:
      - uses: actions/checkout@v4
      - id: py
        name: Run pytest
        uses: ./.github/actions/python-tests
        with:
          python-version: ${{ matrix.python-version }}
          working-directory: '.'
          install-command: 'pip install -r requirements.txt'
          pytest-args: ''

      # Update badges
      - name: Update badges (only on main, py 3.12)
        if: github.ref == 'refs/heads/main' && matrix.python-version == '3.12'
        uses: ./.github/actions/badges-update
        with:
          tests-passed: ${{ steps.py.outputs.tests_passed }}
          coverage-pct:  ${{ steps.py.outputs.coverage_pct }}
          commit-branch: ${{ github.ref_name }}
